#pragma once
#define WIFI_SSID      "YOUR_WIFI_SSID"
#define WIFI_PASS      "YOUR_WIFI_PASSWORD"
#define VOLTIX_API_URL "http://192.168.1.10:3000"
#define GATE_API_KEY   "CHANGE_ME_SUPER_SECRET"   // = VOLTIX_DEVICE_KEY